// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatConfig is the predicate function for chatconfig builders.
type ChatConfig func(*sql.Selector)

// ChatHistory is the predicate function for chathistory builders.
type ChatHistory func(*sql.Selector)

// OpenAIToken is the predicate function for openaitoken builders.
type OpenAIToken func(*sql.Selector)
