// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TBXark/chat-bot-go/pkg/dao/ent/chathistory"
)

// ChatHistoryCreate is the builder for creating a ChatHistory entity.
type ChatHistoryCreate struct {
	config
	mutation *ChatHistoryMutation
	hooks    []Hook
}

// SetChatID sets the "chat_id" field.
func (chc *ChatHistoryCreate) SetChatID(i int64) *ChatHistoryCreate {
	chc.mutation.SetChatID(i)
	return chc
}

// SetContent sets the "content" field.
func (chc *ChatHistoryCreate) SetContent(s string) *ChatHistoryCreate {
	chc.mutation.SetContent(s)
	return chc
}

// Mutation returns the ChatHistoryMutation object of the builder.
func (chc *ChatHistoryCreate) Mutation() *ChatHistoryMutation {
	return chc.mutation
}

// Save creates the ChatHistory in the database.
func (chc *ChatHistoryCreate) Save(ctx context.Context) (*ChatHistory, error) {
	return withHooks[*ChatHistory, ChatHistoryMutation](ctx, chc.sqlSave, chc.mutation, chc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (chc *ChatHistoryCreate) SaveX(ctx context.Context) *ChatHistory {
	v, err := chc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (chc *ChatHistoryCreate) Exec(ctx context.Context) error {
	_, err := chc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chc *ChatHistoryCreate) ExecX(ctx context.Context) {
	if err := chc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (chc *ChatHistoryCreate) check() error {
	if _, ok := chc.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "ChatHistory.chat_id"`)}
	}
	if _, ok := chc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ChatHistory.content"`)}
	}
	return nil
}

func (chc *ChatHistoryCreate) sqlSave(ctx context.Context) (*ChatHistory, error) {
	if err := chc.check(); err != nil {
		return nil, err
	}
	_node, _spec := chc.createSpec()
	if err := sqlgraph.CreateNode(ctx, chc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	chc.mutation.id = &_node.ID
	chc.mutation.done = true
	return _node, nil
}

func (chc *ChatHistoryCreate) createSpec() (*ChatHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatHistory{config: chc.config}
		_spec = sqlgraph.NewCreateSpec(chathistory.Table, sqlgraph.NewFieldSpec(chathistory.FieldID, field.TypeInt))
	)
	if value, ok := chc.mutation.ChatID(); ok {
		_spec.SetField(chathistory.FieldChatID, field.TypeInt64, value)
		_node.ChatID = value
	}
	if value, ok := chc.mutation.Content(); ok {
		_spec.SetField(chathistory.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	return _node, _spec
}

// ChatHistoryCreateBulk is the builder for creating many ChatHistory entities in bulk.
type ChatHistoryCreateBulk struct {
	config
	builders []*ChatHistoryCreate
}

// Save creates the ChatHistory entities in the database.
func (chcb *ChatHistoryCreateBulk) Save(ctx context.Context) ([]*ChatHistory, error) {
	specs := make([]*sqlgraph.CreateSpec, len(chcb.builders))
	nodes := make([]*ChatHistory, len(chcb.builders))
	mutators := make([]Mutator, len(chcb.builders))
	for i := range chcb.builders {
		func(i int, root context.Context) {
			builder := chcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, chcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, chcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, chcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (chcb *ChatHistoryCreateBulk) SaveX(ctx context.Context) []*ChatHistory {
	v, err := chcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (chcb *ChatHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := chcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chcb *ChatHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := chcb.Exec(ctx); err != nil {
		panic(err)
	}
}
