// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TBXark/chat-bot-go/pkg/dao/ent/openaitoken"
	"github.com/TBXark/chat-bot-go/pkg/dao/ent/predicate"
)

// OpenAITokenQuery is the builder for querying OpenAIToken entities.
type OpenAITokenQuery struct {
	config
	ctx        *QueryContext
	order      []openaitoken.OrderOption
	inters     []Interceptor
	predicates []predicate.OpenAIToken
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OpenAITokenQuery builder.
func (oatq *OpenAITokenQuery) Where(ps ...predicate.OpenAIToken) *OpenAITokenQuery {
	oatq.predicates = append(oatq.predicates, ps...)
	return oatq
}

// Limit the number of records to be returned by this query.
func (oatq *OpenAITokenQuery) Limit(limit int) *OpenAITokenQuery {
	oatq.ctx.Limit = &limit
	return oatq
}

// Offset to start from.
func (oatq *OpenAITokenQuery) Offset(offset int) *OpenAITokenQuery {
	oatq.ctx.Offset = &offset
	return oatq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oatq *OpenAITokenQuery) Unique(unique bool) *OpenAITokenQuery {
	oatq.ctx.Unique = &unique
	return oatq
}

// Order specifies how the records should be ordered.
func (oatq *OpenAITokenQuery) Order(o ...openaitoken.OrderOption) *OpenAITokenQuery {
	oatq.order = append(oatq.order, o...)
	return oatq
}

// First returns the first OpenAIToken entity from the query.
// Returns a *NotFoundError when no OpenAIToken was found.
func (oatq *OpenAITokenQuery) First(ctx context.Context) (*OpenAIToken, error) {
	nodes, err := oatq.Limit(1).All(setContextOp(ctx, oatq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{openaitoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oatq *OpenAITokenQuery) FirstX(ctx context.Context) *OpenAIToken {
	node, err := oatq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OpenAIToken ID from the query.
// Returns a *NotFoundError when no OpenAIToken ID was found.
func (oatq *OpenAITokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oatq.Limit(1).IDs(setContextOp(ctx, oatq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{openaitoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oatq *OpenAITokenQuery) FirstIDX(ctx context.Context) int {
	id, err := oatq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OpenAIToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OpenAIToken entity is found.
// Returns a *NotFoundError when no OpenAIToken entities are found.
func (oatq *OpenAITokenQuery) Only(ctx context.Context) (*OpenAIToken, error) {
	nodes, err := oatq.Limit(2).All(setContextOp(ctx, oatq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{openaitoken.Label}
	default:
		return nil, &NotSingularError{openaitoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oatq *OpenAITokenQuery) OnlyX(ctx context.Context) *OpenAIToken {
	node, err := oatq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OpenAIToken ID in the query.
// Returns a *NotSingularError when more than one OpenAIToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (oatq *OpenAITokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oatq.Limit(2).IDs(setContextOp(ctx, oatq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{openaitoken.Label}
	default:
		err = &NotSingularError{openaitoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oatq *OpenAITokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := oatq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OpenAITokens.
func (oatq *OpenAITokenQuery) All(ctx context.Context) ([]*OpenAIToken, error) {
	ctx = setContextOp(ctx, oatq.ctx, "All")
	if err := oatq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OpenAIToken, *OpenAITokenQuery]()
	return withInterceptors[[]*OpenAIToken](ctx, oatq, qr, oatq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oatq *OpenAITokenQuery) AllX(ctx context.Context) []*OpenAIToken {
	nodes, err := oatq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OpenAIToken IDs.
func (oatq *OpenAITokenQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oatq.ctx.Unique == nil && oatq.path != nil {
		oatq.Unique(true)
	}
	ctx = setContextOp(ctx, oatq.ctx, "IDs")
	if err = oatq.Select(openaitoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oatq *OpenAITokenQuery) IDsX(ctx context.Context) []int {
	ids, err := oatq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oatq *OpenAITokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oatq.ctx, "Count")
	if err := oatq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oatq, querierCount[*OpenAITokenQuery](), oatq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oatq *OpenAITokenQuery) CountX(ctx context.Context) int {
	count, err := oatq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oatq *OpenAITokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oatq.ctx, "Exist")
	switch _, err := oatq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oatq *OpenAITokenQuery) ExistX(ctx context.Context) bool {
	exist, err := oatq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OpenAITokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oatq *OpenAITokenQuery) Clone() *OpenAITokenQuery {
	if oatq == nil {
		return nil
	}
	return &OpenAITokenQuery{
		config:     oatq.config,
		ctx:        oatq.ctx.Clone(),
		order:      append([]openaitoken.OrderOption{}, oatq.order...),
		inters:     append([]Interceptor{}, oatq.inters...),
		predicates: append([]predicate.OpenAIToken{}, oatq.predicates...),
		// clone intermediate query.
		sql:  oatq.sql.Clone(),
		path: oatq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OpenAIToken.Query().
//		GroupBy(openaitoken.FieldToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oatq *OpenAITokenQuery) GroupBy(field string, fields ...string) *OpenAITokenGroupBy {
	oatq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OpenAITokenGroupBy{build: oatq}
	grbuild.flds = &oatq.ctx.Fields
	grbuild.label = openaitoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token,omitempty"`
//	}
//
//	client.OpenAIToken.Query().
//		Select(openaitoken.FieldToken).
//		Scan(ctx, &v)
func (oatq *OpenAITokenQuery) Select(fields ...string) *OpenAITokenSelect {
	oatq.ctx.Fields = append(oatq.ctx.Fields, fields...)
	sbuild := &OpenAITokenSelect{OpenAITokenQuery: oatq}
	sbuild.label = openaitoken.Label
	sbuild.flds, sbuild.scan = &oatq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OpenAITokenSelect configured with the given aggregations.
func (oatq *OpenAITokenQuery) Aggregate(fns ...AggregateFunc) *OpenAITokenSelect {
	return oatq.Select().Aggregate(fns...)
}

func (oatq *OpenAITokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oatq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oatq); err != nil {
				return err
			}
		}
	}
	for _, f := range oatq.ctx.Fields {
		if !openaitoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oatq.path != nil {
		prev, err := oatq.path(ctx)
		if err != nil {
			return err
		}
		oatq.sql = prev
	}
	return nil
}

func (oatq *OpenAITokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OpenAIToken, error) {
	var (
		nodes = []*OpenAIToken{}
		_spec = oatq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OpenAIToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OpenAIToken{config: oatq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oatq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (oatq *OpenAITokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oatq.querySpec()
	_spec.Node.Columns = oatq.ctx.Fields
	if len(oatq.ctx.Fields) > 0 {
		_spec.Unique = oatq.ctx.Unique != nil && *oatq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oatq.driver, _spec)
}

func (oatq *OpenAITokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(openaitoken.Table, openaitoken.Columns, sqlgraph.NewFieldSpec(openaitoken.FieldID, field.TypeInt))
	_spec.From = oatq.sql
	if unique := oatq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oatq.path != nil {
		_spec.Unique = true
	}
	if fields := oatq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaitoken.FieldID)
		for i := range fields {
			if fields[i] != openaitoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oatq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oatq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oatq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oatq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oatq *OpenAITokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oatq.driver.Dialect())
	t1 := builder.Table(openaitoken.Table)
	columns := oatq.ctx.Fields
	if len(columns) == 0 {
		columns = openaitoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oatq.sql != nil {
		selector = oatq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oatq.ctx.Unique != nil && *oatq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oatq.predicates {
		p(selector)
	}
	for _, p := range oatq.order {
		p(selector)
	}
	if offset := oatq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oatq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OpenAITokenGroupBy is the group-by builder for OpenAIToken entities.
type OpenAITokenGroupBy struct {
	selector
	build *OpenAITokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oatgb *OpenAITokenGroupBy) Aggregate(fns ...AggregateFunc) *OpenAITokenGroupBy {
	oatgb.fns = append(oatgb.fns, fns...)
	return oatgb
}

// Scan applies the selector query and scans the result into the given value.
func (oatgb *OpenAITokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oatgb.build.ctx, "GroupBy")
	if err := oatgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpenAITokenQuery, *OpenAITokenGroupBy](ctx, oatgb.build, oatgb, oatgb.build.inters, v)
}

func (oatgb *OpenAITokenGroupBy) sqlScan(ctx context.Context, root *OpenAITokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oatgb.fns))
	for _, fn := range oatgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oatgb.flds)+len(oatgb.fns))
		for _, f := range *oatgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oatgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oatgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OpenAITokenSelect is the builder for selecting fields of OpenAIToken entities.
type OpenAITokenSelect struct {
	*OpenAITokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oats *OpenAITokenSelect) Aggregate(fns ...AggregateFunc) *OpenAITokenSelect {
	oats.fns = append(oats.fns, fns...)
	return oats
}

// Scan applies the selector query and scans the result into the given value.
func (oats *OpenAITokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oats.ctx, "Select")
	if err := oats.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpenAITokenQuery, *OpenAITokenSelect](ctx, oats.OpenAITokenQuery, oats, oats.inters, v)
}

func (oats *OpenAITokenSelect) sqlScan(ctx context.Context, root *OpenAITokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oats.fns))
	for _, fn := range oats.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
