// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TBXark/chat-bot-go/pkg/dao/ent/openaitoken"
)

// OpenAIToken is the model entity for the OpenAIToken schema.
type OpenAIToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive     bool `json:"is_active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaitoken.FieldIsActive:
			values[i] = new(sql.NullBool)
		case openaitoken.FieldID:
			values[i] = new(sql.NullInt64)
		case openaitoken.FieldToken:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIToken fields.
func (oat *OpenAIToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaitoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			oat.ID = int(value.Int64)
		case openaitoken.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				oat.Token = value.String
			}
		case openaitoken.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				oat.IsActive = value.Bool
			}
		default:
			oat.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIToken.
// This includes values selected through modifiers, order, etc.
func (oat *OpenAIToken) Value(name string) (ent.Value, error) {
	return oat.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIToken.
// Note that you need to call OpenAIToken.Unwrap() before calling this method if this OpenAIToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (oat *OpenAIToken) Update() *OpenAITokenUpdateOne {
	return NewOpenAITokenClient(oat.config).UpdateOne(oat)
}

// Unwrap unwraps the OpenAIToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (oat *OpenAIToken) Unwrap() *OpenAIToken {
	_tx, ok := oat.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIToken is not a transactional entity")
	}
	oat.config.driver = _tx.drv
	return oat
}

// String implements the fmt.Stringer.
func (oat *OpenAIToken) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", oat.ID))
	builder.WriteString("token=")
	builder.WriteString(oat.Token)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", oat.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAITokens is a parsable slice of OpenAIToken.
type OpenAITokens []*OpenAIToken
