// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/TBXark/chat-bot-go/pkg/dao/ent/openaitoken"
	"github.com/TBXark/chat-bot-go/pkg/dao/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	openaitokenFields := schema.OpenAIToken{}.Fields()
	_ = openaitokenFields
	// openaitokenDescToken is the schema descriptor for token field.
	openaitokenDescToken := openaitokenFields[0].Descriptor()
	// openaitoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	openaitoken.TokenValidator = openaitokenDescToken.Validators[0].(func(string) error)
	// openaitokenDescIsActive is the schema descriptor for is_active field.
	openaitokenDescIsActive := openaitokenFields[1].Descriptor()
	// openaitoken.DefaultIsActive holds the default value on creation for the is_active field.
	openaitoken.DefaultIsActive = openaitokenDescIsActive.Default.(bool)
}
