// Code generated by ent, DO NOT EDIT.

package chatconfig

import (
	"entgo.io/ent/dialect/sql"
	"github.com/TBXark/chat-bot-go/pkg/dao/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldLTE(FieldID, id))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldEQ(FieldChatID, v))
}

// JSON applies equality check predicate on the "json" field. It's identical to JSONEQ.
func JSON(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldEQ(FieldJSON, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v int64) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldLTE(FieldChatID, v))
}

// JSONEQ applies the EQ predicate on the "json" field.
func JSONEQ(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldEQ(FieldJSON, v))
}

// JSONNEQ applies the NEQ predicate on the "json" field.
func JSONNEQ(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldNEQ(FieldJSON, v))
}

// JSONIn applies the In predicate on the "json" field.
func JSONIn(vs ...string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldIn(FieldJSON, vs...))
}

// JSONNotIn applies the NotIn predicate on the "json" field.
func JSONNotIn(vs ...string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldNotIn(FieldJSON, vs...))
}

// JSONGT applies the GT predicate on the "json" field.
func JSONGT(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldGT(FieldJSON, v))
}

// JSONGTE applies the GTE predicate on the "json" field.
func JSONGTE(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldGTE(FieldJSON, v))
}

// JSONLT applies the LT predicate on the "json" field.
func JSONLT(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldLT(FieldJSON, v))
}

// JSONLTE applies the LTE predicate on the "json" field.
func JSONLTE(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldLTE(FieldJSON, v))
}

// JSONContains applies the Contains predicate on the "json" field.
func JSONContains(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldContains(FieldJSON, v))
}

// JSONHasPrefix applies the HasPrefix predicate on the "json" field.
func JSONHasPrefix(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldHasPrefix(FieldJSON, v))
}

// JSONHasSuffix applies the HasSuffix predicate on the "json" field.
func JSONHasSuffix(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldHasSuffix(FieldJSON, v))
}

// JSONEqualFold applies the EqualFold predicate on the "json" field.
func JSONEqualFold(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldEqualFold(FieldJSON, v))
}

// JSONContainsFold applies the ContainsFold predicate on the "json" field.
func JSONContainsFold(v string) predicate.ChatConfig {
	return predicate.ChatConfig(sql.FieldContainsFold(FieldJSON, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatConfig) predicate.ChatConfig {
	return predicate.ChatConfig(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatConfig) predicate.ChatConfig {
	return predicate.ChatConfig(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatConfig) predicate.ChatConfig {
	return predicate.ChatConfig(func(s *sql.Selector) {
		p(s.Not())
	})
}
